### ISSUE TITLE
Mouse Movement 

### ISSUE THREAD

**Issue by ghost** [AbleDabble/ObjDet-Aimbot#1]
Hello, I have a problem with the aimbot... it's running for me, it says Aimbot Active, the aimbot screen shows and it's detecting the players correctly, but aimbot is not working... the crosshair is not moving and I can't hold my left mouse button it only allows one-click I don't know why this is happening or I'm just not using it correctly or there's a toggle button that you didn't mention.
Please help/fix it.
**I tried it on Fortnite**

**Comment by ghost** [comment]
Update: i figured out how it works but the left mouse still click once ( i cant hold when i hold it just press once)

Edit: I just removed the triggerbot thing from testing.py file and holding is working!

**Comment by AbleDabble** [comment]
The trigger bot works by scanning reticle color in the center of the screen every frame releasing the mouse button if the enemy color isn't present hence why you are unable to hold the mouse button down. Removing it is probably the best option if you are trying to get it to work on a different game.

**Comment by ghost** [comment]
Yes actully fortnite doesnt need a trigger bot, i may use it in valorant but the mouse movement does not work in valorant i think its anticheat block it, thats sad 🥲 anyways are you going to improve and update the code? because its dope ❤️
